### PR TITLE
feat: support a limited use case of `allOf` keyword

### PR DESCRIPTION
**Pull request by alexander-matsievsky**
The use case refers to adding constraints to the core schema.
I.e. `{"allOf":["<core schema>",{"anyOf":["<constraints>"]}]}`

### CODE REVIEW

**Comment by alexander-matsievsky** [comment]
This change makes possible to express the statement:
> The instance must contain `YEAR` for sure, `DATE` if possible.
> If it contains `DATE`, the `YEAR` must be specified as well.

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "allOf": [
    {
      "type": "object",
      "required": [
        "COUNTRY"
      ],
      "properties": {
        "COUNTRY": {
          "type": "string"
        },
        "DATE": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        },
        "YEAR": {
          "type": "string",
          "pattern": "^\\d{4}$"
        },
        "RELEASE_TYPE": {
          "type": "string"
        }
      }
    },
    {
      "anyOf": [
        {
          "type": "object",
          "required": [
            "DATE",
            "YEAR"
          ]
        },
        {
          "type": "object",
          "required": [
            "YEAR"
          ]
        }
      ]
    }
  ]
}
```

**Comment by starrify** [comment]
Thanks @alexander-matsievsky for the changes. Unfortunately I'm against merging it to this repo and / or the upstream one at `scrapy-plugins/scrapy-jsonschema`.

My reasons:
1. The solution (of picking from `schema['allOf'][0]['properties']`) is too specific. It's probably designed for only the very example you provided.
2. And it's not _right_ (although right for your very example). It merely avoids the crashes in some cases, and in some other cases it may make things even worse (e.g. no crash to have developers notified but the resulting schema would be incorrect).

Suggestions:
1. I suppose the best solution is to simply update the schema. There's at least one equivalent form of your example which is much better.
2. If you do need such ad-hoc code applied, you probably could do that inside your project. And it's strongly suggested to apply the "fix" to only the specific schema you find breaking, instead of all possible schemas (see also: my reason 2 above).
3. The whole existing changes here in `starrify:add-merge-schema` are just workarounds for some basic cases. You may consider implementing a better one to cover all possible schemas (e.g. the example you provided), but that probably would take some time.

**Comment by alexander-matsievsky** [comment]
@starrify Thanks for reviewing my PR!

Could you please elaborate on the first suggestion a bit? If I understand it correctly, `scrapy-jsonschema` assumes the schema is an [`object` type with `properties` defined](https://github.com/scrapy-plugins/scrapy-jsonschema/blob/master/scrapy_jsonschema/item.py#L18), so `allOf`, `anyOf`, `oneOf` keywords are forbidden. What would be the equivalent form which allows to specify these `DATE`/`YEAR` constraints?

**Comment by alexander-matsievsky** [comment]
@starrify BTW I created this PR with a broken heart, as I totally agree with you that this is a very hacky work-around to support JSON Schema's `allOf` keyword.

**Comment by starrify** [comment]
@alexander-matsievsky  Sorry for not having provided an example earlier. I was hurrying for a meeting and was thinking of doing that right after it. :sweat_smile: 

I've rewritten your sample schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "required": [
    "COUNTRY",
    "YEAR"
  ],
  "properties": {
    "COUNTRY": {
      "type": "string"
    },
    "DATE": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "YEAR": {
      "type": "string",
      "pattern": "^\\d{4}$"
    },
    "RELEASE_TYPE": {
      "type": "string"
    }
  }
}
```
And I think those two are just equivalent. Can you please help reviewing it and let me know if you find any counter examples (e.g. one JSON object that is valid according to one schema but not to the other).

Also, regarding:

> scrapy-jsonschema assumes the schema is an object type with properties defined, so allOf, anyOf, oneOf keywords are forbidden.

IIRC you must have a top-level `properties` attribute provided when using `scrapy-jsonschema`, but meanwhile it's fine to use those keywords in lower levels (e.g. inside definition of one property).

**Comment by alexander-matsievsky** [comment]
@starrify Incredible! That's what's called missing the forest for the trees+) Somehow I've convinced myself the solution necessitates advanced schema features, and kept running with this assumption...

Many thanks to you, Peng-Yu! Have a nice day!

**Comment by starrify** [comment]
@alexander-matsievsky My pleasure. :)

Besides, for the generic cases of `{"allOf":["<core schema>",{"anyOf":["<constraints>"]}]}` I think you may always make it as `{"properties": <core schema>, "anyOf" (or "allOf"): [<constrains>]}`. And example:

```python
>>> import jsonschema
>>> schema = {
...   "type": "object",
...   "properties": {
...     "foo": {
...       "type": "string"
...     },
...     "bar": {
...       "type": "string",
...     },
...   },
...   "anyOf": [
...     {
...       "properties": {
...         "foo": {
...           "maxLength": 4,
...         },
...       },
...     },
...     {
...       "properties": {
...         "bar": {
...           "maxLength": 4,
...         },
...       },
...     },
...   ]
... }
>>> jsonschema.validate({'foo': 'looooong', 'bar': 'shrt'}, schema)
>>> jsonschema.validate({'foo': 'looooong', 'bar': 'loooooong'}, schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pengyu/temp/env/lib/python3.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/pengyu/temp/env/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: {'foo': 'looooong', 'bar': 'loooooong'} is not valid under any of the given schemas

Failed validating 'anyOf' in schema:
    {'anyOf': [{'properties': {'foo': {'maxLength': 4}}},
               {'properties': {'bar': {'maxLength': 4}}}],
     'properties': {'bar': {'type': 'string'}, 'foo': {'type': 'string'}},
     'type': 'object'}

On instance:
    {'bar': 'loooooong', 'foo': 'looooong'}
```

Furthermore, if a constraint involves only one property (e.g. a date string may be either `YYYYMMDD` or `YYYY-MM-DD`) you may put it inside a property, instead of at top-level.

**Comment by alexander-matsievsky** [comment]
@starrify Thanks one more time! I really appreciate your answers!

**Pull request closed without merging**
